#roles>network>tasks>terminate.yml

- name: Get VPC Info
  amazon.aws.ec2_vpc_net_info:
    region: "{{ region }}"
    filters: { "tag:Name": "{{ prefix}}-vpc"}
  register: vpc_info

- name : Terminate Network VPC
  when : vpc_info.vpcs | length > 0
  block:
    - set_fact:
    target_vpc_id: "{{ vpc_info.vpcs[0].vpc_id }}"